# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master

jobs:
- job: Build
  displayName: 'Build'
  pool:
    name: Default # Replace MySelfHostedAgentPool with the name of your self-hosted agent pool
    demands: # Add specific demands if required for your self-hosted agent
      - Agent.Name -equals MONEYKICKS # Replace MySelfHostedAgent with the name of your self-hosted agent
  steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'dotnet build $(buildConfiguration)'
