# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - azure-pipelines

variables:
  buildConfiguration: 'Release'
  RestoreBuildProjects: '**/*.csproj'

jobs:
- job: Build
  displayName: 'Build'
  pool:
    name: Default # Replace MySelfHostedAgentPool with the name of your self-hosted agent pool
    demands: # Add specific demands if required for your self-hosted agent
      - Agent.Name -equals MONEYKICKS # Replace MySelfHostedAgent with the name of your self-hosted agent
  steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restore'
    inputs:
      command: restore
      projects: '$(RestoreBuildProjects)'

  - task: DotNetCoreCLI@2
    displayName: 'Build'
    inputs:
      command: build
      projects: '$(RestoreBuildProjects)'
      arguments: '--configuration $(buildConfiguration)'
